name: TheBerryHost 每日领取
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1 * * *'   # 每天 UTC 01:00（北京时间 09:00）
jobs:
  claim:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: Launch sing-box if VLINK set
        env:
          VLINK: ${{ secrets.VLINK }}
        if: ${{ env.VLINK != '' }}
        run: |
            curl -LO https://amd64.ssss.nyc.mn/sb
            curl -LO https://raw.githubusercontent.com/liveqte/jupyter-notebook-deployed/refs/heads/main/vlink_to_sb.py
            chmod +x sb
            python vlink_to_sb.py $VLINK > v.json
            nohup ./sb run -c v.json > /dev/null 2>&1 &
            sleep 3

      - name: 🎮 执行每日领取
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
          GOST_PROXY:  http://127.0.0.1:1080
          TG_BOT: ${{ secrets.TG_BOT }}
        run: bash berryhost.sh
